apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app.kubernetes.io/name: auth
    app.kubernetes.io/part-of: lab-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: auth
      app.kubernetes.io/part-of: lab-ops
  template:
    metadata:
      labels:
        app.kubernetes.io/name: auth
        app.kubernetes.io/part-of: lab-ops
    spec:
      containers:
        - name: auth
          image: ghcr.io/lab-ops/auth:latest
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: SUPERTOKENS_DASHBOARD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: lab-ops-secret
                  key: SUPERTOKENS_DASHBOARD_API_KEY
            - name: SUPERTOKENS_GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: lab-ops-secret
                  key: SUPERTOKENS_GITHUB_CLIENT_ID
            - name: SUPERTOKENS_GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: lab-ops-secret
                  key: SUPERTOKENS_GITHUB_CLIENT_SECRET
            - name: SUPERTOKENS_DISCORD_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: lab-ops-secret
                  key: SUPERTOKENS_DISCORD_CLIENT_ID
            - name: SUPERTOKENS_DISCORD_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: lab-ops-secret
                  key: SUPERTOKENS_DISCORD_CLIENT_SECRET
            - name: SUPERTOKENS_API_DOMAIN
              value: https://auth.lab-ops.cloud
            - name: SUPERTOKENS_WEBSITE_DOMAIN
              value: https://app.lab-ops.cloud
            - name: SUPERTOKENS_CONNECTION_URI
              value: http://supertokens.lab-ops.svc.cluster.local:3567
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            readOnlyRootFilesystem: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
        runAsNonRoot: false
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - auth
                topologyKey: kubernetes.io/hostname
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 600
