on:
  push:
    branches:
      - main

name: release-please

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
      - name: Checkout
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/checkout@v3
      - name: Docker Metadata
        if: ${{ steps.release.outputs.releases_created }}
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/lab-ops/auth
      - name: Build and Push Container
        if: ${{ steps.release.outputs.releases_created }}
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
